### ISSUE TITLE
Post your performance metrics here.

### ISSUE THREAD

**Issue by Titaniumtown** [KibbleLands/KibblePatcher#2]
Could you add in a section in the readme about how much faster the server can be with and with out this patcher?

**Comment by Nooffy** [comment]
We are tired at the moment, thank you for your suggestion.

**Comment by JRoy** [comment]
> We are tired at the moment, thank you for your suggestion.

Did you get enough rest to post performance metrics yet?

**Comment by Fox2Code** [comment]
Me and Vakea weren't able to work on the project at the time the issue was closed.
I will reopen it to not forget to do some performances metrics, myself.

Since one features of the patcher is the plugin rewrite, the result can varies if the server has a lot of plugins.
(Thank @JRoy for asking, but sadly even if we got better, we still didn't fully recovered yet)

Also everyone is welcome to post their own metric here, if it contain metrics both with and without the patcher.

**Comment by Fox2Code** [comment]
I will temporary let everyone post their metrics here until I do proper metrics.

I don't think it would be as simple as testing one time with and one time without as there are a lots of things that can affect how much performances is gained this the patcher such what fork or Minecraft version is used, what plugins are installed, how many players are online, and probably more.

A big difference of this "optimization" tool compared to most server forks like Paper, is that it also optimize loaded plugins.

But I am really curious how much the patcher optimize the server, and how in which situation the patcher give the most and fewest performances gain.

**Comment by Fox2Code** [comment]
Yeah nah, I think I will probably remove optimizations from the project and just keep the features, I recently made some breakthrough in optimization, and with how I have been treated with this project I don't want to make this breakthrough opensource.

The main point of this project was about "Plugin compatibility" (For fun), and new APIs for a server that has been abandoned.  
(The main thing about this project was to make some parts of the server open source)

The optimizations was a plus that wasn't the main goal of the project.
`1.7.x` version will just be maintenance update, and for `1.8.x` I will remove all optimization code.

I admit I made some mistakes at the beginning of the project, but I didn't deserved to be treated like shit because of that.

Since I will removing all optimization features in a future update I'm closing this issue now.
