### ISSUE TITLE
An optimisation has failed in an unexpected way. please report the issue with your server jar!

### ISSUE THREAD

**Issue by xhmr** [KibbleLands/KibblePatcher#4]
When building a little bit changed TacoSpigot 1.8.

java -jar KibblePatcher-1.3.jar taco.jar server-patched.jar
ÔľÂ Reading jar...
ÔľÂ Pawtching jar...
An optimisation has failed in an unexpected way. please report the issue with your server jar!
NMS: v1_8_R3
Debug state: GetPlayerItemNotFound
ÔľÂ Building jar...
ÔľÂ Writing jar...
ÔľÂ Generic optimiser:
ÔľÂ   Optimised java calls: 21
ÔľÂ   Optimised opcodes: 1646
ÔľÂ   Optimised forEach: 0
ÔľÂ Finished!

ÔľÂ Server patcher:
ÔľÂ   Compatibility patches: 4
ÔľÂ   Optimisations patches: 6
ÔľÂ   Security patches: 1
ÔľÂ   Plugin rewrite: UNSUPPORTED

**Comment by xhmr** [comment]
Maybe I can't use it with this java version?
java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**Comment by xhmr** [comment]
On java 1.9 same thing.

**Comment by Fox2Code** [comment]
The fails is not a critical fails, it just affect a security patch to avoid a server crash exploit.
You should be able to launch the server with KibblePatcher 1.4 without problem.

I recommend you to install this plugin since it also fix the book crash exploit:
https://www.spigotmc.org/resources/custompayloadfixer-bungeecord-bukkit-spigot.39891/
(My patch is complementary with the protection of this plugin but both can work individually without any problem)

I will investigate this issue and fix it in the next release

**Comment by xhmr** [comment]
@Fox2Code how to fix that?

**Comment by Fox2Code** [comment]
@assasin541 There is no need to fix that if you use the plugin I gave you

But TacoSpigot probably chages the code in a way KibblePatcher didn't excepted

**Comment by Fox2Code** [comment]
@assasin541 
I couldn't reproduce the bug with the TacoSpigot I downloaded.
Please provide a download link to the current server jar that you are currently using.

**Comment by xhmr** [comment]
@Fox2Code what is this error about and why it can't proceed in my situation?

**Comment by Fox2Code** [comment]
Because KibblePatcher expect the code to have a specific structure and the jar you are using doesn't follow this code structure.
It's why I need the server jar, because if I can't have access to it, I can't adapt the patcher to your jar code.

**Comment by Fox2Code** [comment]
As I have no way of reproducing the issue I will close it, 
please understand that in most cases I can't fix issues if I can't reproduce them.

If you have a way for me to reproduce the issue, you can open a new issue with the step to how reproducing it.
As I am unable to reproduce and you didn't provided a way to reproduce the issue, this issue is closed.

**Comment by xhmr** [comment]
@Fox2Code you didn't say how the code have to look or something.
